version: '3.3'

services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - "27017:27017"
  web:
    build: "./"
    command:  "npm run start"
    ports: 
      - "3000:3000"
    environment:
      DB_URI: mongodb://root:example@db:27017
      PORT: 3000
